name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bugfix
      - fix
      - bug
  - title: 🛠 Refactoring
    labels:
      - refactoring
  - title: 📖 Documentation
    labels:
      - documentation
  - title: 🧰 Maintenance
    labels:
      - dependencies
template: |
  ## Changes
  $CHANGES
